apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z10o
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-z10o@sha256:9826b6a51994a488ebc21f273d86c92db80dfe560fb30f653afe02a3a2a08236
        name: my-nodejs
        resources: {}
status: {}
